/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal projects and is checked in here
// so the paid-platform scaffold type-checks cleanly after dependencies install.

