insert into public.metagame_signature_rules
  (format, card_name, archetype_name, required_colors, priority, notes)
values
  ('Modern', 'Galvanic Discharge', 'Jeskai Energy', array['W','U','R'], 150, 'Opening Edge default archetype rule.'),
  ('Modern', 'Galvanic Discharge', 'Boros Energy', array['W','R'], 140, 'Opening Edge default archetype rule.'),
  ('Modern', 'Mox Opal', 'Affinity', array['U','R'], 130, 'Opening Edge default archetype rule.'),
  ('Modern', 'Goryo''s Vengeance', 'Goryo''s Vengeance', array[]::text[], 140, 'Opening Edge default archetype rule.'),
  ('Modern', 'Thought-Knot Seer', 'Eldrazi Tron', array['Colorless'], 145, 'Opening Edge default archetype rule.'),
  ('Modern', 'Manamorphose', 'Ruby Storm', array['W','R'], 130, 'Opening Edge default archetype rule.'),
  ('Modern', 'Monastery Swiftspear', 'Izzet Prowess', array['U','R'], 130, 'Opening Edge default archetype rule.'),
  ('Modern', 'Cleansing Wildfire', 'Boros Ponza', array['W','R'], 120, 'Opening Edge default archetype rule.'),
  ('Modern', 'Kozilek''s Command', 'RG Eldrazi', array['R','G'], 140, 'Opening Edge default archetype rule.'),
  ('Modern', 'Abhorrent Oculus', 'Grixis Reanimator', array['U','B','R'], 130, 'Opening Edge default archetype rule.'),
  ('Modern', 'Amulet of Vigor', 'Amulet Titan', array[]::text[], 130, 'Opening Edge default archetype rule.'),
  ('Modern', 'Solitude', 'Esper Generic Blink', array['W','U','B'], 120, 'Opening Edge default archetype rule.'),
  ('Modern', 'Living End', 'Living End', array['U','B'], 130, 'Opening Edge default archetype rule.'),
  ('Modern', 'Territorial Kavu', 'Domain Zoo', array['W','U','B','R','G'], 130, 'Opening Edge default archetype rule.'),
  ('Modern', 'Yawgmoth, Thran Physician', 'Yawgmoth', array[]::text[], 130, 'Opening Edge default archetype rule.'),

  ('Standard', 'Ouroboroid', 'Selesnya Ouroboroid', array['W','G'], 130, 'Opening Edge default archetype rule.'),
  ('Standard', 'Slickshot Show-Off', 'Izzet Prowess', array['U','R'], 130, 'Opening Edge default archetype rule.'),
  ('Standard', 'Jeskai Revelation', 'Jeskai Lessons', array['W','U','R'], 130, 'Opening Edge default archetype rule.'),
  ('Standard', 'Tablet of Discovery', '4c Control', array['W','U','B','R'], 130, 'Opening Edge default archetype rule.'),
  ('Standard', 'Eddymurk Crab', 'Izzet Spellementals', array['U','R'], 130, 'Opening Edge default archetype rule.'),
  ('Standard', 'Doomsday Excruciator', 'Dimir Excruciator', array['U','B'], 130, 'Opening Edge default archetype rule.'),
  ('Standard', 'Icetill Explorer', 'Mono-Green Landfall', array['G'], 130, 'Opening Edge default archetype rule.'),
  ('Standard', 'Moonshadow', 'Mardu Discard', array['W','B','R'], 130, 'Opening Edge default archetype rule.'),
  ('Standard', 'Gran-Gran', 'Izzet Lessons', array['U','R'], 130, 'Opening Edge default archetype rule.'),
  ('Standard', 'Mightform Harmonizer', 'Selesnya Landfall', array['W','G'], 130, 'Opening Edge default archetype rule.'),
  ('Standard', 'Brightglass Gearhulk', '4c Gearhulk', array['W','U','R','G'], 140, 'Opening Edge default archetype rule.'),
  ('Standard', 'Hired Claw', 'Mono-Red Aggro', array['R'], 130, 'Opening Edge default archetype rule.'),
  ('Standard', 'Slickshot Show-Off', 'Izzet Spells', array['U','R'], 120, 'Opening Edge default archetype rule.'),
  ('Standard', 'Momo, Friendly Flier', 'Azorius Momo', array['W','U'], 130, 'Opening Edge default archetype rule.'),
  ('Standard', 'Brightglass Gearhulk', 'Selesnya Gearhulk', array['W','G'], 130, 'Opening Edge default archetype rule.'),

  ('Pioneer', 'Monastery Swiftspear', 'Izzet Prowess', array['U','R'], 140, 'Opening Edge default archetype rule.'),
  ('Pioneer', 'Monastery Swiftspear', 'Mono-Red Prowess', array['R'], 130, 'Opening Edge default archetype rule.'),
  ('Pioneer', 'Thoughtseize', 'Golgari Midrange', array['B','G'], 130, 'Opening Edge default archetype rule.'),
  ('Pioneer', 'No More Lies', 'Azorius Control', array['W','U'], 130, 'Opening Edge default archetype rule.'),
  ('Pioneer', 'Greasefang, Okiba Boss', 'Abzan Greasefang', array['W','B','G'], 140, 'Opening Edge default archetype rule.'),
  ('Pioneer', 'Greasefang, Okiba Boss', 'Orzhov Greasefang', array['W','B'], 130, 'Opening Edge default archetype rule.'),
  ('Pioneer', 'Kaito, Bane of Nightmares', 'Dimir Midrange', array['U','B'], 130, 'Opening Edge default archetype rule.'),
  ('Pioneer', 'Arclight Phoenix', 'Izzet Phoenix', array['U','R'], 130, 'Opening Edge default archetype rule.'),
  ('Pioneer', 'Ouroboroid', 'Selesnya Counters', array['W','G'], 130, 'Opening Edge default archetype rule.'),
  ('Pioneer', 'Gran-Gran', 'Izzet Lessons', array['U','R'], 130, 'Opening Edge default archetype rule.'),
  ('Pioneer', 'Fatal Push', 'Mono-Black Midrange', array['B'], 120, 'Opening Edge default archetype rule.'),
  ('Pioneer', 'Thoughtseize', 'Dimir Aggro', array['U','B'], 130, 'Opening Edge default archetype rule.'),
  ('Pioneer', 'Vivi Ornitier', 'Izzet Midrange', array['U','R'], 130, 'Opening Edge default archetype rule.'),
  ('Pioneer', 'Scapeshift', '5c Scapeshift', array['W','U','B','R','G'], 140, 'Opening Edge default archetype rule.'),
  ('Pioneer', 'Scapeshift', 'Simic Scapeshift', array['U','G'], 130, 'Opening Edge default archetype rule.'),

  ('Legacy', 'Daze', 'Izzet Delver', array['U','R'], 130, 'Opening Edge default archetype rule.'),
  ('Legacy', 'Thoughtseize', 'Dimir Tempo', array['U','B'], 130, 'Opening Edge default archetype rule.'),
  ('Legacy', 'Reanimate', 'Rakdos Reanimator', array['U','B','R','G'], 130, 'Opening Edge default archetype rule.'),
  ('Legacy', 'Doomsday', 'Doomsday', array['U','B','G'], 130, 'Opening Edge default archetype rule.'),
  ('Legacy', 'Show and Tell', 'Sneak and Show', array['U','B','R'], 130, 'Opening Edge default archetype rule.'),
  ('Legacy', 'Mox Opal', 'Blue Artifacts', array['W','U','R'], 130, 'Opening Edge default archetype rule.'),
  ('Legacy', 'Life from the Loam', 'Lands', array['W','R','G'], 130, 'Opening Edge default archetype rule.'),
  ('Legacy', 'Ocelot Pride', 'Mardu Energy', array['W','B','R'], 140, 'Opening Edge default archetype rule.'),
  ('Legacy', 'Burning Wish', 'The EPIC Storm', array['W','U','B','R','G'], 130, 'Opening Edge default archetype rule.'),
  ('Legacy', 'Ocelot Pride', 'Boros Energy', array['W','R'], 130, 'Opening Edge default archetype rule.'),
  ('Legacy', 'The Fantasticar', 'Dimir Car', array['U','B'], 140, 'Opening Edge default archetype rule.'),
  ('Legacy', 'Force of Will', 'Azorius Control', array['W','U'], 120, 'Opening Edge default archetype rule.'),
  ('Legacy', 'Painter''s Servant', 'Painter', array['U','B','R'], 130, 'Opening Edge default archetype rule.'),
  ('Legacy', 'Thought-Knot Seer', 'Eldrazi', array['R'], 130, 'Opening Edge default archetype rule.'),
  ('Legacy', 'The Fantasticar', 'Car Stompy', array['W'], 130, 'Opening Edge default archetype rule.')
on conflict (format, card_name, archetype_name, required_colors)
do update set
  priority = excluded.priority,
  notes = excluded.notes,
  is_active = true,
  updated_at = now();
